MCP_SERVERS_KEY = "mcpServers"

DEFAULT_MODEL = "(bedrock)us.anthropic.claude-3-7-sonnet-20250219-v1:0"
DEFAULT_TOKEN_THRESHOLD = 150000
DEFAULT_MAX_TOOL_TOKENS = 50000
DEFAULT_TOKENIZER_MODEL = "o200k_base"

# Default reasoning settings
DEFAULT_BUDGET_TOKENS = 4096
DEFAULT_REASONING_ENABLED = True
